services:
  postgres:
    image: postgres:17
    container_name: diti4-postgres
    environment:
      POSTGRES_DB: diti4_pring_mvc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diti4_pring_mvc"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: diti4-spring-mvc-final
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/diti4_pring_mvc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: